# Define the goal
bool start_tracker
string name_object
---
# Define the result
geometry_msgs/Point[] trajectory
---
# Define feedback
bool is_valid
float32 delta_altitude
geometry_msgs/Point target_pos
float32 intercept_delta
float32 intercept_time
geometry_msgs/Point[] intercept

